name: Update Formula Versions

on:
  schedule:
    - cron: "0 6 * * *" # Run daily at 6 AM UTC
  workflow_dispatch: # Allow manual trigger

jobs:
  update-formulas:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install requests

      - name: Update sl formula
        id: update-sl
        run: |
          python scripts/update-sl.py

      - name: Update zpiral formula
        id: update-zpiral
        run: |
          python scripts/update-zpiral.py

      - name: Update opencode formula
        id: update-opencode
        run: |
          python scripts/update-opencode.py

      - name: Check for changes
        id: check-changes
        run: |
          if git diff --quiet; then
            echo "changes=false" >> $GITHUB_OUTPUT
            echo "No changes detected"
          else
            echo "changes=true" >> $GITHUB_OUTPUT
            echo "Changes detected"
          fi

      - name: Create Pull Request
        if: steps.check-changes.outputs.changes == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Configure git
          git config user.email "action@github.com"
          git config user.name "GitHub Action"

          # Create and switch to a new branch
          git checkout -b update-formulas

          # Add and commit changes
          git add .
          git commit -m "chore: update formula versions"

          # Push the branch
          git push origin update-formulas

          # Create pull request using GitHub CLI
          gh pr create \
            --title "chore: update formula versions" \
            --body "Automated update of formula versions to latest releases.

          This PR was automatically created by the update workflow." \
            --head update-formulas \
            --base main \
            --assignee "@me"
